### ISSUE TITLE
data_admin is not created

### ISSUE THREAD

**Issue by cuhde** [ease-crc/openease#2]
The data_admin container is not created after admin login. Furthermore docker logs admin is not available due to this (Fresh install). After that OpenEASE is stuck at "Loading Knowledge Base" when selecting episode data.

dockerbridge     | 172.18.0.2 - - [16/Aug/2019 15:02:16] "POST / HTTP/1.1" 200 -
dockerbridge     | Creating data_admin container.
dockerbridge     | Creating data_admin container.
dockerbridge     | Error in create_user_data_container: 404 Client Error: Not Found for url: http+docker://localunixsocket/v1.18/containers/create?name=data_admin
dockerbridge     | Error in create_user_data_container: 404 Client Error: Not Found for url: http+docker://localunixsocket/v1.18/containers/create?name=data_admin
dockerbridge     | Traceback (most recent call last):
dockerbridge     |   File "/opt/dockerbridge/dockermanager.py", line 94, in create_user_data_container
dockerbridge     |     volumes=['/etc/rosauth'], entrypoint='true')
dockerbridge     |   File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 135, in create_container
dockerbridge     |     return self.create_container_from_config(config, name)
dockerbridge     |   File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 146, in create_container_from_config
dockerbridge     |     return self._result(res, True)
dockerbridge     |   File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 178, in _result
dockerbridge     |     self._raise_for_status(response)
dockerbridge     |   File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 173, in _raise_for_status
dockerbridge     |     raise errors.NotFound(e, response, explanation=explanation)
dockerbridge     | NotFound: 404 Client Error: Not Found ("No such image: knowrob/user_data:latest")

============================================

openease         | --------------------------------------------------------------------------------
openease         | ERROR in docker_interface [/opt/webapp/webrob/docker/docker_interface.py:233]:
openease         | ConnectionError during file_ls: 404 Client Error: Not Found ("No such container: data_admin")Traceback (most recent call last):
openease         |   File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
openease         |     result = rpc_function(*positional_params, **named_params)
openease         |   File "dockerbridge.py", line 177, in files_ls
openease         |     return filemanager.listfiles(container, file, recursive)
openease         |   File "/opt/dockerbridge/filemanager.py", line 144, in listfiles
openease         |     find = self.__find(container, dir, opts)
openease         |   File "/opt/dockerbridge/filemanager.py", line 187, in __find
openease         |     cont = self.__create_temp_container('sh -c \'cd '+dir+' && find .'+opts+'\'', data_container)
openease         |   File "/opt/dockerbridge/filemanager.py", line 221, in __create_temp_container
openease         |     "VolumesFrom": [data_container] })
openease         |   File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 135, in create_container
openease         |     return self.create_container_from_config(config, name)
openease         |   File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 146, in create_container_from_config
openease         |     return self._result(res, True)
openease         |   File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 178, in _result
openease         |     self._raise_for_status(response)
openease         |   File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 173, in _raise_for_status
openease         |     raise errors.NotFound(e, response, explanation=explanation)
openease         | NotFound: 404 Client Error: Not Found ("No such container: data_admin")
openease         | 
openease         | 
openease         | --------------------------------------------------------------------------------
openease         | ConnectionError during file_ls: 404 Client Error: Not Found ("No such container: data_admin")Traceback (most recent call last):
openease         |   File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
openease         |     result = rpc_function(*positional_params, **named_params)
openease         |   File "dockerbridge.py", line 177, in files_ls
openease         |     return filemanager.listfiles(container, file, recursive)
openease         |   File "/opt/dockerbridge/filemanager.py", line 144, in listfiles
openease         |     find = self.__find(container, dir, opts)
openease         |   File "/opt/dockerbridge/filemanager.py", line 187, in __find
openease         |     cont = self.__create_temp_container('sh -c \'cd '+dir+' && find .'+opts+'\'', data_container)
openease         |   File "/opt/dockerbridge/filemanager.py", line 221, in __create_temp_container
openease         |     "VolumesFrom": [data_container] })
openease         |   File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 135, in create_container
openease         |     return self.create_container_from_config(config, name)
openease         |   File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 146, in create_container_from_config
openease         |     return self._result(res, True)
openease         |   File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 178, in _result
openease         |     self._raise_for_status(response)
openease         |   File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 173, in _raise_for_status
openease         |     raise errors.NotFound(e, response, explanation=explanation)
openease         | NotFound: 404 Client Error: Not Found ("No such container: data_admin")
openease         | 
openease         | 
openease         | ERROR:webrob.app_and_db:ConnectionError during file_ls: 404 Client Error: Not Found ("No such container: data_admin")Traceback (most recent call last):
openease         |   File "/usr/local/lib/python2.7/dist-packages/pyjsonrpc/rpclib.py", line 114, in call
openease         |     result = rpc_function(*positional_params, **named_params)
openease         |   File "dockerbridge.py", line 177, in files_ls
openease         |     return filemanager.listfiles(container, file, recursive)
openease         |   File "/opt/dockerbridge/filemanager.py", line 144, in listfiles
openease         |     find = self.__find(container, dir, opts)
openease         |   File "/opt/dockerbridge/filemanager.py", line 187, in __find
openease         |     cont = self.__create_temp_container('sh -c \'cd '+dir+' && find .'+opts+'\'', data_container)
openease         |   File "/opt/dockerbridge/filemanager.py", line 221, in __create_temp_container
openease         |     "VolumesFrom": [data_container] })
openease         |   File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 135, in create_container
openease         |     return self.create_container_from_config(config, name)
openease         |   File "/usr/local/lib/python2.7/dist-packages/docker/api/container.py", line 146, in create_container_from_config
openease         |     return self._result(res, True)
openease         |   File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 178, in _result
openease         |     self._raise_for_status(response)
openease         |   File "/usr/local/lib/python2.7/dist-packages/docker/client.py", line 173, in _raise_for_status
openease         |     raise errors.NotFound(e, response, explanation=explanation)
openease         | NotFound: 404 Client Error: Not Found ("No such container: data_admin")
openease         | 
openease         | 
openease         | --------------------------------------------------------------------------------
openease         | ERROR in knowrob [/opt/webapp/webrob/pages/knowrob.py:222]:
openease         | Unhandled Exception: 'NoneType' object has no attribute '__getitem__'
openease         | --------------------------------------------------------------------------------
openease         | Unhandled Exception: 'NoneType' object has no attribute '__getitem__'
openease         | ERROR:webrob.app_and_db:Unhandled Exception: 'NoneType' object has no attribute '__getitem__'
openease         | --------------------------------------------------------------------------------
openease         | ERROR in knowrob [/opt/webapp/webrob/pages/knowrob.py:223]:
openease         | Traceback (most recent call last):
openease         |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
openease         |     rv = self.dispatch_request()
openease         |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
openease         |     return self.view_functions[rule.endpoint](**req.view_args)
openease         |   File "/opt/webapp/webrob/pages/editor.py", line 105, in pkg_list
openease         |     files = filter(lambda s: s['isdir'], docker_interface.file_ls(session['user_container_name'], '.')['children'])
openease         | TypeError: 'NoneType' object has no attribute '__getitem__'
openease         | 
openease         | --------------------------------------------------------------------------------
openease         | Traceback (most recent call last):
openease         |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
openease         |     rv = self.dispatch_request()
openease         |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
openease         |     return self.view_functions[rule.endpoint](**req.view_args)
openease         |   File "/opt/webapp/webrob/pages/editor.py", line 105, in pkg_list
openease         |     files = filter(lambda s: s['isdir'], docker_interface.file_ls(session['user_container_name'], '.')['children'])
openease         | TypeError: 'NoneType' object has no attribute '__getitem__'
openease         | 
openease         | ERROR:webrob.app_and_db:Traceback (most recent call last):
openease         |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1639, in full_dispatch_request
openease         |     rv = self.dispatch_request()
openease         |   File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1625, in dispatch_request
openease         |     return self.view_functions[rule.endpoint](**req.view_args)
openease         |   File "/opt/webapp/webrob/pages/editor.py", line 105, in pkg_list
openease         |     files = filter(lambda s: s['isdir'], docker_interface.file_ls(session['user_container_name'], '.')['children'])
openease         | TypeError: 'NoneType' object has no attribute '__getitem__'
openease         |

**Comment by cuhde** [comment]
I got further by manually downloading two images:
docker pull knowrob/user_data:latest
docker pull openease/kinetic-knowrob-daemon:latest

I am now able to log in, call "docker logs admin", load episode data etc.
Queries work also. Now i am stuck with not having meshes load correctly but i assume this will be a new ticket.

**Comment by daniel86** [comment]
Thanks for the report! I will have a look into why these images are not auto-downloaded

**Comment by daniel86** [comment]
dockerbridge now auto-pulls knowrob/user_data
