### ISSUE TITLE
Error after logging in

### ISSUE THREAD

**Issue by kidSoba** [ease-crc/openease#3]
When logging in and doing other actions, such as selecting the Prolog & OWL Editor, a weird pop-up message containing HTML-Code is displayed. See picture:

![Screenshot from 2019-08-27 12-47-41](https://user-images.githubusercontent.com/43848620/63765312-09359900-c8c9-11e9-99fe-21d16558cd49.png)

No idea what causes this or how this might be linked to other issues.

**Comment by daniel86** [comment]
thanks for the report. I was seeing this once or twice before. I'll have a look at it

**Comment by daniel86** [comment]
I don't think this happens anymore
