### ISSUE TITLE
Unable to download mesh

### ISSUE THREAD

**Issue by cuhde** [ease-crc/openease#3]
When loading an episode with .dae meshes in the episode folder, an error appears for all objects in terminal and nothing is displayed in OpenEASE. It seems like it tries to add /meshes in front of the path:

openease         | INFO:webrob.app_and_db:Unable to download mesh ICS-TUM/automatica_dining_room/meshes/cupboard_door_left.dae
openease         | --------------------------------------------------------------------------------
openease         | INFO in meshes [/opt/webapp/webrob/pages/meshes.py:71]:
openease         | Unable to download mesh ICS-TUM/automatica_dining_room/meshes/movable_door_right_cupboard.dae
openease         | --------------------------------------------------------------------------------
openease         | Unable to download mesh ICS-TUM/automatica_dining_room/meshes/movable_door_right_cupboard.dae
nginx            | 127.0.0.1 - - [20/Aug/2019:12:43:05 +0000] "GET /meshes/ICS-TUM/automatica_dining_room/meshes/movable_door_right_cupboard.dae HTTP/1.1" 200 21 "http://localhost/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0" "-"
nginx            | localhost 127.0.0.1 - - [20/Aug/2019:12:43:05 +0000] "GET /meshes/ICS-TUM/automatica_dining_room/meshes/movable_door_right_cupboard.dae HTTP/1.1" 200 21 "http://localhost/" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0"

**Comment by daniel86** [comment]
The /meshes prefix is used to select a particular route in flask. That is fine.
The suffix gets appended to the /mesh_data directory to get the full path.

Did you added your mesh repo to the environment variables? Have you checked where it is stored in the mesh_data volume?

**Comment by cuhde** [comment]
The meshes are currently stored in "/episodes/ICS-TUM/automatica_dining_room/meshes/", so in the episodes folder itself. They are referred the same way in the semantic map: 

<srdl2-comp:mesh_filename rdf:datatype="&xsd;string">/episodes/ICS-TUM/automatica_dining_room/meshes/fork_small.dae</srdl2-comp:mesh_filename>
        <knowrob:pathToCadModel rdf:datatype="&xsd;string">/episodes/ICS-TUM/automatica_dining_room/meshes/fork_small.dae</knowrob:pathToCadModel>

this works in the pre-rework version from february 2019. But if this is not supported anymore, i will set up a repository.

**Comment by cuhde** [comment]
i additionally put the meshes into a repository and export that as "$OPENEASE_MESHES" but it seems they are not downloaded/located correctly.

**Comment by daniel86** [comment]
> i additionally put the meshes into a repository and export that as "$OPENEASE_MESHES" but it seems they are not downloaded/located correctly.

So you have had a look in the volume and the meshes were not downloaded? You can do so by calling `docker exec -it openease /bin/bash`. Then in `/home/ros/mesh_data` there should by a folder with your repo checked out.

**Comment by daniel86** [comment]
> The meshes are currently stored in "/episodes/ICS-TUM/automatica_dining_room/meshes/", so in the episodes folder itself. They are referred the same way in the semantic map:
> 
> <srdl2-comp:mesh_filename rdf:datatype="&xsd;string">/episodes/ICS-TUM/automatica_dining_room/meshes/fork_small.dae</srdl2-comp:mesh_filename>
> <knowrob:pathToCadModel rdf:datatype="&xsd;string">/episodes/ICS-TUM/automatica_dining_room/meshes/fork_small.dae</knowrob:pathToCadModel>
> 
> this works in the pre-rework version from february 2019. But if this is not supported anymore, i will set up a repository.

that does not work at the moment. All meshes need to be in `/home/ros/mesh_data` in the openease container. This will change soon, when we start storing them together with the episode data. However, might still be required then to have them in a versioned repository.

**Comment by cuhde** [comment]
Okay i checked the path in the openease container and modified my mesh repository to reflect the correct directory in the semantic map (could have done it the other way around ofc). All meshes are loaded correctly now :)
