### ISSUE TITLE
Screen Overlay never goes away

### ISSUE THREAD

**Issue by kidSoba** [ease-crc/openease#4]
The i-Frames Screen overlay (I suppose, I am not entirely sure), does not go away, even when all necessary information is loaded. For example when I request the user data, it stays there until I manually touch the CSS-code inside the developer tools in the browser, even though all information is loaded. See pictures:

![Screenshot from 2019-08-27 12-56-17](https://user-images.githubusercontent.com/43848620/63765886-49e1e200-c8ca-11e9-889c-80af951f48b9.png)
![Screenshot from 2019-08-27 12-57-39](https://user-images.githubusercontent.com/43848620/63765887-49e1e200-c8ca-11e9-8a03-27f0eb6a52b2.png)
![Screenshot from 2019-08-27 12-57-45](https://user-images.githubusercontent.com/43848620/63765888-4a7a7880-c8ca-11e9-9b99-7d4c37c2f943.png)

**Comment by daniel86** [comment]
This does not happen here or for Constantin, apparently. not sure how I can reproduce it
