### ISSUE TITLE
MongoDB querying error

### ISSUE THREAD

**Issue by cuhde** [ease-crc/openease#5]
I loaded our episodes data into OpenEASE and tried to query the semantic map at a specific timepoint. This worked in the February version of OpenEASE. Now i get querying errors talking about out of memory issues. I already created indices for the tf collection:
db.tf.createIndex({"transforms.header.stamp" : 1})
db.tf.createIndex({"__recorded" : +1})

When querying the semantic map at a specific time i get the following mongo error:

mongo            | 2019-08-22T11:10:00.818+0000 E  QUERY    [conn2] Plan executor error during find: FAILURE, stats: { stage: "PROJECTION_SIMPLE", nReturned: 0, executionTimeMillisEstimate: 118, works: 110084, advanced: 0, needTime: 110082, needYield: 0, saveState: 2978, restoreState: 2978, isEOF: 0, transformBy: { transforms: 1 }, inputStage: { stage: "SORT", nReturned: 0, executionTimeMillisEstimate: 117, works: 110084, advanced: 0, needTime: 110082, needYield: 0, saveState: 2978, restoreState: 2978, isEOF: 0, sortPattern: { transforms.header.stamp: -1 }, memUsage: 33554726, memLimit: 33554432, inputStage: { stage: "SORT_KEY_GENERATOR", nReturned: 110081, executionTimeMillisEstimate: 105, works: 110082, advanced: 110081, needTime: 1, needYield: 0, saveState: 2978, restoreState: 2978, isEOF: 0, inputStage: { stage: "FETCH", nReturned: 110081, executionTimeMillisEstimate: 62, works: 110081, advanced: 110081, needTime: 0, needYield: 0, saveState: 2978, restoreState: 2978, isEOF: 0, docsExamined: 110081, alreadyHasObj: 0, inputStage: { stage: "IXSCAN", nReturned: 110081, executionTimeMillisEstimate: 38, works: 110081, advanced: 110081, needTime: 0, needYield: 0, saveState: 2978, restoreState: 2978, isEOF: 0, keyPattern: { transforms.header.stamp: -1.0 }, indexName: "transforms.header.stamp_-1", isMultiKey: true, multiKeyPaths: { transforms.header.stamp: [ "transforms" ] }, isUnique: false, isSparse: false, isPartial: false, indexVersion: 2, direction: "forward", indexBounds: { transforms.header.stamp: [ "(new Date(493200581), true)" ] }, keysExamined: 110081, seeks: 1, dupsTested: 110081, dupsDropped: 0 } } } } }
mongo            | 2019-08-22T11:10:00.932+0000 I  QUERY    [conn2] assertion OperationFailed: Executor error during OP_QUERY find :: caused by :: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit. ns:ICS-TUM_automatica_dining_room.tf query:{ $query: { transforms.header.stamp: { $lt: new Date(493200581) } }, $orderby: { transforms.header.stamp: -1 } }
mongo            | 2019-08-22T11:10:00.932+0000 I  COMMAND  [conn2] query ICS-TUM_automatica_dining_room.tf command: { find: "tf", filter: { transforms.header.stamp: { $lt: new Date(493200581) } }, sort: { transforms.header.stamp: -1 } } planSummary: IXSCAN { transforms.header.stamp: -1 } ntoreturn:0 ntoskip:0 numYields:2978 queryHash:8D9B5F29 planCacheKey:00993FBA ok:0 errMsg:"Executor error during OP_QUERY find :: caused by :: Sort operation used more than the maximum 33554432 bytes of RAM. Add an index, or specify a smaller limit." errName:OperationFailed errCode:96 reslen:232 locks:{ ReplicationStateTransition: { acquireCount: { w: 2979 } }, Global: { acquireCount: { r: 2979 } }, Database: { acquireCount: { r: 2979 } }, Collection: { acquireCount: { r: 2979 } }, Mutex: { acquireCount: { r: 1 } } } storage:{ data: { bytesRead: 93735004, timeReadingMicros: 155170 } } 3706ms

**Comment by cuhde** [comment]
It looks like the index is not enough? Maybe we need to loop with query limits?

**Comment by daniel86** [comment]
I haven't seen this error before.
Did something change in the mongo code? Could be, I'll have a look.

What is the `+` doing here?
db.tf.createIndex({"__recorded" : **+1**})

**Comment by cuhde** [comment]
the +1 is just a mirror of the -1, can be written as 1

**Comment by daniel86** [comment]
I cannot find any change in knowrob_mongo that might introduce this problem

**Comment by cuhde** [comment]
I'll test on another computer, to be sure.

**Comment by daniel86** [comment]
Could you test whether you have a working index?
I know that under some circumstances mongo won't be happy with indexing TF arrays.
Specifically when the array elements have different time stamps.

**Comment by cuhde** [comment]
Do you mean this?:

> db.tf.ensureIndex({"transforms.header.stamp" : 1})
{
        "numIndexesBefore" : 5,
        "numIndexesAfter" : 5,
        "note" : "all indexes already exist",
        "ok" : 1
}

**Comment by cuhde** [comment]
Okay, I took a different subset of episodes and tested with that. Queries work with this subset. I suspect that I didn't record the tf data robustly enough so that all episodes work.

**Comment by daniel86** [comment]
No I meant to do a query vie the mongo console and then `*.explain()` the result, but probably the error would be raised before the result is passed to explain.

Still, would be good to know what the problem is with these episodes. I only had issues before with TF data where arrays were published with elements having different timestamps. So the TF publisher is worth a look to check if it is ensured that each TF msg in the published array has identical timestamp.

Note that Andrei stores TF data generally in map frame, and with one mongo collection per TF frame instead. We will push for unifying this soon, and I assume will patch our fork of the mongo db logger to store TF messages in the right format,
