### ISSUE TITLE
Client fails to connect to Websocket

### ISSUE THREAD

**Issue by kidSoba** [ease-crc/openease#5]
After logging in, the browser console shows this:

![Screenshot from 2019-08-27 12-53-58](https://user-images.githubusercontent.com/43848620/63765642-c7f1b900-c8c9-11e9-93d9-babe8715eb1f.png)

There seems to be some connection error and the sockets fail to connect or alike. We assume this also causes other errors, such as mentioned in issue #3, #4.

**Comment by daniel86** [comment]
Well this is not really a bug. It tries to connect but ROS is not up yet in the docker container. After some time it should succeed to connect.
