### ISSUE TITLE
Mongodb data sychronization failed

### ISSUE THREAD

**Issue by zihexu** [ease-crc/openease#6]
Dear developer,
I wanted to load the mongo db bson files. Already tried with own data failed, so download the data from Visual-Games_Clean-table which should have perfect structure and queries to test.
First, try to download Virtual-Games_clean table to /epside path
![Screenshot from 2019-09-25 23-45-30](https://user-images.githubusercontent.com/38068244/65644109-b51af300-dff3-11e9-96e3-f82d9764aa7d.png)
Then register robcog, load one opisode, then connect_to_db return true, but when press sychronization, lost connection again, as image shows below.
![Screenshot from 2019-09-25 22-36-44](https://user-images.githubusercontent.com/38068244/65644152-d4198500-dff3-11e9-817d-a59b0ccae8c1.png)
And the docker logs admin returns error as image below, from the last line it said no collection, the same as my own data.
![Screenshot from 2019-09-25 22-34-05](https://user-images.githubusercontent.com/38068244/65644322-3ecac080-dff4-11e9-9437-a9838171e85d.png)
![Screenshot from 2019-09-25 22-34-14](https://user-images.githubusercontent.com/38068244/65644324-40948400-dff4-11e9-9223-228d7175f68d.png)
What could be the problem?

**Comment by daniel86** [comment]
Hello, sorry for the delay, I was not in office the last weeks.

The messages show that the JS client cannot connect to the ROS service *json_prolog*. It is common that it takes sonme time until the service is up, and that these messages are written out when the JS client tries to early.
There also has been a change in KnowRob, *json_prolog* is no more, it is now called *rosprolog*. So it could be that it tries to connect to the service with outdated names.

Generally speaking, it is always hard to guess what is wrong when it is unclear what the versions in use are. So You are already using the openEASE version that is started with docker-compose?
In that case you should provide the full console output from the terminal where you called compose up. This might indicate something to me.

**Comment by daniel86** [comment]
I close this issue because there was no response for some time.
